/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#bdc7d8',
        'on-tertiary-fixed': '#121c28',
        'on-secondary-container': '#5e656c',
        'primary-fixed-dim': '#adc7ff',
        'primary-container': '#1a73e8',
        'on-primary-container': '#ffffff',
        'on-tertiary-fixed-variant': '#3e4755',
        'secondary-container': '#dce3eb',
        'surface-dim': '#d3daef',
        'on-error-container': '#93000a',
        background: '#f9f9ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#d9e3f4',
        'surface-container-low': '#f1f3ff',
        'secondary-fixed': '#dce3eb',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001a41',
        'outline-variant': '#c1c6d6',
        'on-background': '#141b2b',
        outline: '#727785',
        secondary: '#585f66',
        'inverse-primary': '#adc7ff',
        'surface-container-highest': '#dce2f7',
        'on-surface': '#141b2b',
        'inverse-on-surface': '#edf0ff',
        'on-tertiary-container': '#ffffff',
        'on-secondary-fixed-variant': '#40484e',
        'on-primary': '#ffffff',
        'surface-tint': '#005bc0',
        'primary-fixed': '#d8e2ff',
        'surface-container': '#e9edff',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#004493',
        'secondary-fixed-dim': '#c0c7cf',
        'on-secondary-fixed': '#151c22',
        'on-surface-variant': '#414754',
        primary: '#005bbf',
        'inverse-surface': '#293040',
        'surface-variant': '#dce2f7',
        tertiary: '#545e6d',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'surface-container-high': '#e1e8fd',
        'surface-bright': '#f9f9ff',
        'tertiary-container': '#6d7786',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        lg: '40px',
        md: '24px',
        sm: '12px',
        'container-max': '1200px',
        xs: '4px',
        xl: '64px',
      },
      fontFamily: {
        'label-md': ['Manrope', 'sans-serif'],
        caption: ['Manrope', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
        h2: ['Manrope', 'sans-serif'],
        h3: ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        h1: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        h2: ['30px', { lineHeight: '1.3', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        h1: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
